sudo: required
services:
  - docker

before_install:
  - docker build -t nikhilgb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nikhilgb/react-test npm test -- --coverage

after_success:
  - docker build -t nikhilgb/multi-client ./client
  - docker build -t nikhilgb/multi-nginx ./nginx
  - docker build -t nikhilgb/multi-server ./server
  - docker build -t nikhilgb/multi-worker ./worker
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  - docker push nikhilgb/multi-client:latest
  - docker push nikhilgb/multi-nginx:latest
  - docker push nikhilgb/multi-server:latest
  - docker push nikhilgb/multi-worker:latest

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: multi-docker-env
  bucket_name: elasticbeanstalk-ap-south-1-069653090426
  bucket_path: docker-mutli
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
